---


- name: Create Drupal database.
  mysql_db: >
    login_user={{ mysql_admin_user }}
    login_password={{ mysql_admin_password }}
    db={{ drupal_mysql_database }}
    state=present

- name: Create a MySQL user for Drupal.
  mysql_user: >
    login_user={{ mysql_admin_user }}
    login_password={{ mysql_admin_password }}
    name={{ drupal_mysql_user }}
    host={{ item }}
    priv={{ drupal_mysql_database }}.*:ALL
    password={{ drupal_mysql_password }}
    state=present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

