---

##Install Drupal if not installed
#
######################################################################
#

- name: Check if Drupal is already installed in {{ drupal_site_path }}.
  stat: path="{{ drupal_site_path }}/sites/default/settings.php"
  register: drupal_installed

- name: Install Drupal (standard profile) with drush from {{ drupal_site_path }}.
  command: "{{drush_location}}  si -y --site-name='{{ drupal_site_name }}' --account-name='{{ drupal_account_name }}' --account-pass='{{ drupal_account_pass }}' --db-url=mysql://{{ drupal_mysql_user }}:{{ drupal_mysql_password }}@localhost/{{ drupal_mysql_database }}"
  args:
    chdir: "{{ drupal_site_path }}"
  notify:
    - restart webserver
  when:
    - drupal_installed.stat.exists == false

