---

- name: Does vhost file exist?
  stat: path=/etc/apache2/sites-available/{{ drupal_domain }}.conf
  register: vhost_exists

- name: Create vhost file for {{ drupal_domain }} on drupalvm installs
  template:
    src=templates/{{ drupal_env }}_vhost_template.j2
    dest=/etc/apache2/sites-available/{{ drupal_domain }}.conf
  when: not vhost_exists.stat.exists

  notify:
    - restart apache2

- name: a2ensite {{ drupal_domain }}.conf
  command: a2ensite {{ drupal_domain }}.conf
  when: not vhost_exists.stat.exists

  notify:
  - restart apache2
